<a href="https://colab.research.google.com/github/maheshwarampranay/PAI-lab/blob/main/PAI_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Water Jug Problem

In [ ]:
from collections import deque

def WaterJugBFS(jug1,jug2,target):
  #if not possible return karo
  if target > max(jug1,jug2):
    return False
  #create a set to track visited nodes
  visited = set()
  visited.add((0,0))
  #create a parent mapping to map parent node of every visited node
  parent = {(0,0):None}
  #finally a queue to run BFS
  queue = deque()
  queue.append((0,0))
  #let's loop
  while queue:
    #Extract the left most element
    current = queue.popleft()
    a,b=current
    #inspect if it is solution
    if a==target or b==target:
      #if yes, extract path and return
      path = []
      while current is not None:
        path.append(current)
        current = parent[current]
      path.reverse()
      return path
    #else we geenrate all children of the current state and go on searching!
    generated = [(jug1,b),(a,jug2),(0,b),(a,0),(max(0, a-(jug2-b)), min(b+a, jug2)), (min(a+b,jug1), max(0, b-(jug1-a)))]
    for next_state in generated:
        if next_state not in visited:
          visited.add(next_state)
          queue.append(next_state)
          parent[next_state]=current
  return False


WaterJugBFS(5,7,4)

[(0, 0), (0, 7), (5, 2), (0, 2), (2, 0), (2, 7), (5, 4)]

In [ ]:
def WaterJugDFS(jug1,jug2,target):
  visited = set()
  path = []

  def dfs(a,b):
    if (a,b) in visited:
      return False
    visited.add((a,b))
    path.append((a,b))
    if a == target:
      path.append((a,0))
      return True
    if b==target:
      path.append((0,b))
      return True
    if dfs(0,b):
      return True
    if dfs(jug1,b):
      return True
    if dfs(a,0):
      return True
    if dfs(a,jug2):
      return True
    if dfs(max(0, a-(jug2-b)), min(b+a, jug2)):
      return True
    if dfs(min(a+b,jug1), max(0, b-(jug1-a))):
      return True
    path.pop()
    return False

  if dfs(0,0):
    return path
  return False

WaterJugDFS(5,7,4)

[(0, 0),
 (5, 0),
 (5, 7),
 (0, 7),
 (5, 2),
 (0, 2),
 (2, 0),
 (2, 7),
 (5, 4),
 (0, 4)]

In [ ]:
#Water jug using A star
import heapq
def WaterJugAstar(jug1, jug2, goal):
  def is_goal(state):
    return state[0]==goal
  def heuristic(state):
    return abs(state[0]-goal)
  def get_neighbours(state):
    a,b = state
    neighbours = [(jug1,b),(a,jug2),(0,b),(a,0),(max(0, a-(jug2-b)), min(b+a, jug2)), (min(a+b,jug1), max(0, b-(jug1-a)))]
    return neighbours

  visited = set()
  pq = []
  start = (0,0)
  heapq.heappush(pq, (heuristic(start),0,start, [start]))

  while pq:
    f, g, current, path = heapq.heappop(pq)
    if current in visited:
      continue
    visited.add(current)

    if is_goal(current):
      return path

    for neighbour in get_neighbours(current):
      if neighbour not in visited:
        g = g+1
        f = g+heuristic(neighbour)
        heapq.heappush(pq, (f,g,neighbour, path+[neighbour]))
  return None

print(WaterJugAstar(4,3,2))

[(0, 0), (4, 0), (1, 3), (1, 0), (0, 1), (4, 1), (2, 3)]


#A-star algorithm

In [ ]:
# Graph represented as an adjacency list with edge costs
graph = {
    'A': {'B': 1, 'C': 4},
    'B': {'D': 5, 'E': 12},
    'C': {'F': 2},
    'D': {'G': 3},
    'E': {'G': 1},
    'F': {'E': 3},
    'G': {}
}

# Heuristic values for each node (straight-line distance to goal 'G')
h = {
    'A': 10,
    'B': 8,
    'C': 5,
    'D': 7,
    'E': 3,
    'F': 6,
    'G': 0
}


def Astar_search(start, stop):
  open_set = [start]
  closed_set= set()
  parents={}
  g={}
  g[start]=0
  parents[start]=None

  while open_set:
    current = None
    for node in open_set:
      if current==None or g[node]+h[node]<g[current]+h[current]:
        current = node
    if current is None:
      return None
    if current == stop:
      path=[]
      while parents[current]!=None:
        path.append(current)
        current = parents[current]
      path.append(start)
      path.reverse()
      return path
    open_set.remove(current)
    closed_set.add(current)
    if graph.get(current) is None:
      continue
    for (n,w) in graph.get(current):
      if n in closed_set:
        continue
      if n not in open_set:
        parents[n]=current
        g[n]=g[current]+w
        open_set.append(n)
      else:
        if g[n]>g[n]+w:
          g[n]=g[n]+w
          parents[n]=current
          if n in closed_set:
            closed_set.remove(n)
            open_set.append(n)
  return False


#8-puzzle solver

In [ ]:
import heapq
goal=[1,2,3,4,5,6,7,8,0]

def heuristic(state):
  distance=0
  for i in range(9):
    if state[i]!=0:
      goal_pos=goal.index(state[i])
      distance+=abs(i//3-goal_pos//3)+abs(i%3-goal_pos%3)
  return distance

def next_states(state):
  moves = []
  idx=state.index(0)
  row, col = idx//3, idx%3
  directions = [(-1,0),(1,0),(0,1),(0,-1)]
  for dr, dc in directions:
    new_row, new_col = row+dr, col+dc
    if 0<=new_row<3 and 0<new_col<3:
      new_idx = new_row*3+new_col
      new_state = state[:]
      new_state[new_idx], new_state[idx] =new_state[idx], new_state[new_idx]
      moves.append(new_state)
  return moves


def a_star(initial):
  open_list = []
  heapq.heappush(open_list, (heuristic(initial),0,initial,[]))

  visited = set()
  visited.add(tuple(initial))

  while open_list:
    f,g,current_state, path = heapq.heappop(open_list)
    if current_state == goal:
      return path + [current_state]
    for neighbour in next_states(current_state):
      if tuple(neighbour) not in visited:
        visited.add(tuple(neighbour))
        h = heuristic(neighbour)
        heapq.heappush(open_list, (g+h+1,g+1, neighbour, path+[current_state]))
  return None

def format_state(state):
  return [state[i:i+3] for i in range(0,9,3)]

start = [1,2,3,4,8,0,7,6,5]

solution = a_star(start)

if solution:
  print("solution:")
  for i in solution:
    for row in format_state(i):
      print(row)
    print()
else:
  print("NO SOLUTION FOUND!")


solution:
[1, 2, 3]
[4, 8, 0]
[7, 6, 5]

[1, 2, 3]
[4, 8, 5]
[7, 6, 0]

[1, 2, 3]
[4, 8, 5]
[7, 0, 6]

[1, 2, 3]
[4, 0, 5]
[7, 8, 6]

[1, 2, 3]
[4, 5, 0]
[7, 8, 6]

[1, 2, 3]
[4, 5, 6]
[7, 8, 0]



#CSP

In [ ]:
def solve_n_queens(n):
  board = [['.' for _ in range(n)] for _ in range(n)]
  solutions = []

  def is_safe(row, col):
    #check for same column
    for i in range(row):
      if board[i][col] == 'Q':
        return False

    #check  diagonals
    i,j = row-1, col-1
    while i>=0 and j>=0:
      if board[i][j] == 'Q':
        return False
      i-=1
      j-=1

    i,j = row-1, col+1
    while i>=0 and j<n:
      if board[i][j]=='Q':
        return False
      i-=1
      j+=1
    return True

  def backtrack(row):
    if row==n:
      solutions.append([''.join(r) for r in board])
      return
    for col in range(n):
      if is_safe(row, col):
        board[row][col] = 'Q'
        backtrack(row+1)
        board[row][col] = '.'
  backtrack(0)
  return solutions
n=int(input("Enter n for N-Queens"))
solutions = solve_n_queens(n)
for i in range(len(solutions)):
    print(f"solution {i+1}")
    for row in solutions[i]:
      print(row)
    print()

Enter n for N-Queens4
solution 1
.Q..
...Q
Q...
..Q.

solution 2
..Q.
Q...
...Q
.Q..



#GAME SEARCH

In [ ]:
#mini max search
import math
def minimax(current_depth, node_index, max_turn, scores, target_depth):
  if current_depth == target_depth:
    return scores[node_index]
  if max_turn:
    return max(minimax(current_depth+1, node_index*2, False, scores, target_depth), minimax(current_depth+1, node_index*2+1, False, scores, target_depth))
  else:
    return min(minimax(current_depth+1, node_index*2, True, scores, target_depth), minimax(current_depth+1, node_index*2+1, True, scores, target_depth))

scores=[3,5,2,9,12,5,23,23]
tree_depth = int(math.log2(len(scores)))
print("The optimal value is:", minimax(0,0,True,scores,tree_depth))

The optimal value is: 12


In [ ]:
MAX, MIN = float('inf'), float('-inf')
def aplhabetapruning(depth, node_index, max_turn, scores,target_depth, alpha, beta):
  if depth == target_depth:
    return scores[node_index]
  if max_turn:
    best = MIN
    for i in range(2):
      val = aplhabetapruning(depth+1, node_index*2+i, False, scores, target_depth, alpha, beta)
      best = max(best, val)
      alpha = max(best, alpha)
      if beta <= alpha:
        break
    return best
  else:
    best = MAX
    for i in range(2):
      val = aplhabetapruning(depth+1, node_index*2+i, True, scores, target_depth, alpha, beta)
      best = min(best, val)
      beta = min(beta, best)
      if beta<=alpha:
        break
    return best

scores = [3,5,6,9,1,2,0,7]
target_depth=math.log2(len(scores))
print("Optimal value is:", aplhabetapruning(0,0,True,scores,target_depth, MIN, MAX))

Optimal value is: 5


#Bayesian Network

In [ ]:
!pip install kagglehub
!pip install pgmpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 24.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 756.0/756.0 kB 30.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 14.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 23.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 61.7 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("johnsmith88/heart-disease-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/heart-disease-dataset


In [ ]:
import pandas as pd
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination

data = pd.read_csv('/kaggle/input/heart-disease-dataset/heart.csv')
data.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [ ]:
heart_disease_predictor = DiscreteBayesianNetwork([
    ('age','target'), ('chol', 'fbs'), ('chol', 'target'),
    ('oldpeak', 'target')
])

In [ ]:
heart_disease_predictor.fit(data, estimator=MaximumLikelihoodEstimator)

In [ ]:
infer = VariableElimination(heart_disease_predictor)

In [ ]:
#Querying
q = infer.query(['target'], evidence={'age':54})
print(q)

+-----------+---------------+
| target    |   phi(target) |
+===========+===============+
| target(0) |        0.4957 |
+-----------+---------------+
| target(1) |        0.5043 |
+-----------+---------------+


#MDP

In [ ]:
import numpy as np

grid = [[0,0,0,1],
        [0,None,0,-1],
        [0,0,0,0]]

rows, cols = len(grid), len(grid[0])
default_reward = -0.1
gamma = 0.9
theta = 1e-3

actions=['U','L','R','D']

action_delta = {
    'U':(-1,0),
    'L':(0,-1),
    'R':(0,1),
    'D':(1,0)
}

transitions = {
    'U':[('U',0.8), ('L',0.1), ('R',0.1)],
    'L':[('U',0.1), ('L',0.8), ('D',0.1)],
    'R':[('U',0.1), ('R',0.8), ('D',0.1)],
    'D':[('L',0.1), ('R',0.1), ('D',0.8)]
}

def is_valid(r,c):
  return 0<=r<rows and 0<=c<cols and grid[r][c] is not None

def get_reward(r,c):
  return grid[r][c] if grid[r][c] is not None else default_reward
def is_terminal(r,c):
  return grid[r][c] in [1,-1]

In [ ]:
def value_iteration():
    V = np.zeros((rows, cols))
    policy = [['' for _ in range(cols)] for _ in range(rows)]
    iteration = 0

    while True:
        delta = 0
        new_V = np.copy(V)

        print(f"\nIteration {iteration}:")
        for r in range(rows):
            for c in range(cols):
                if grid[r][c] is None:
                    continue  # Skip wall

                if is_terminal(r, c):
                    new_V[r][c] = grid[r][c]
                    continue  # Terminal state

                best_value = float('-inf')
                best_action = None

                for a in actions:
                    total = 0
                    for move, prob in transitions[a]:
                        dr, dc = action_delta[move]
                        nr, nc = r + dr, c + dc

                        if not is_valid(nr, nc):
                            nr, nc = r, c  # stay in place if invalid move

                        reward = grid[nr][nc] if is_terminal(nr, nc) else default_reward
                        total += prob * (reward + gamma * V[nr][nc])

                    if total > best_value:
                        best_value = total
                        best_action = a

                new_V[r][c] = best_value
                policy[r][c] = best_action
                delta = max(delta, abs(V[r][c] - best_value))

        V = new_V
        print(np.round(V, 2))  # Print current value function

        iteration += 1
        if delta < theta:
            break

    return V, policy

# Run value iteration
V, policy = value_iteration()

# Print final results
print("\nFinal Value Function:")
print(np.round(V, 2))

print("\nFinal Policy:")
for row in policy:
    print(' '.join([a if a else '.' for a in row]))


Iteration 0:
[[-0.1  -0.1   0.78  1.  ]
 [-0.1   0.   -0.1  -1.  ]
 [-0.1  -0.1  -0.1  -0.1 ]]

Iteration 1:
[[-0.19  0.44  1.56  1.  ]
 [-0.19  0.    0.27 -1.  ]
 [-0.19 -0.19 -0.19 -0.19]]

Iteration 2:
[[ 0.19  1.1   1.67  1.  ]
 [-0.27  0.    0.87 -1.  ]
 [-0.27 -0.27  0.06 -0.27]]

Iteration 3:
[[ 0.69  1.3   1.73  1.  ]
 [-0.02  0.    1.   -1.  ]
 [-0.34 -0.1   0.48 -0.26]]

Iteration 4:
[[ 0.89  1.38  1.75  1.  ]
 [ 0.39  0.    1.05 -1.  ]
 [-0.15  0.22  0.59  0.04]]

Iteration 5:
[[ 1.01  1.4   1.75  1.  ]
 [ 0.61  0.    1.07 -1.  ]
 [ 0.19  0.36  0.68  0.14]]

Iteration 6:
[[ 1.06  1.41  1.75  1.  ]
 [ 0.74  0.    1.08 -1.  ]
 [ 0.39  0.46  0.72  0.22]]

Iteration 7:
[[ 1.08  1.42  1.75  1.  ]
 [ 0.79  0.    1.08 -1.  ]
 [ 0.51  0.5   0.74  0.26]]

Iteration 8:
[[ 1.09  1.42  1.76  1.  ]
 [ 0.82  0.    1.08 -1.  ]
 [ 0.56  0.52  0.75  0.27]]

Iteration 9:
[[ 1.09  1.42  1.76  1.  ]
 [ 0.83  0.    1.08 -1.  ]
 [ 0.59  0.53  0.75  0.28]]

Iteration 10:
[[ 1.09  1.42  1.76  1.  

In [ ]:
#Policy Iternation
import numpy as np

# Grid configuration
grid = [
    [0,  0,   0,  +1],
    [0, None, 0,  -1],
    [0,  0,   0,   0]
]

rows, cols = len(grid), len(grid[0])

# Rewards
default_reward = -0.1
gamma = 0.9
theta = 1e-4

actions = ['U', 'L', 'D', 'R']
action_delta = {
    'U': (-1, 0),
    'D': (1, 0),
    'L': (0, -1),
    'R': (0, 1)
}

transitions = {
    'U': [('U', 0.8), ('L', 0.1), ('R', 0.1)],
    'D': [('D', 0.8), ('R', 0.1), ('L', 0.1)],
    'L': [('L', 0.8), ('D', 0.1), ('U', 0.1)],
    'R': [('R', 0.8), ('U', 0.1), ('D', 0.1)]
}

def is_valid(r, c):
    return 0 <= r < rows and 0 <= c < cols and grid[r][c] is not None

def is_terminal(r, c):
    return grid[r][c] in [+1, -1]

def policy_evaluation(policy, V):
    while True:
        delta = 0
        new_V = np.copy(V)

        for r in range(rows):
            for c in range(cols):
                if grid[r][c] is None or is_terminal(r, c):
                    continue

                a = policy[r][c]
                total = 0
                for move, prob in transitions[a]:
                    dr, dc = action_delta[move]
                    nr, nc = r + dr, c + dc

                    if not is_valid(nr, nc):
                        nr, nc = r, c

                    reward = grid[nr][nc] if is_terminal(nr, nc) else default_reward
                    total += prob * (reward + gamma * V[nr][nc])

                new_V[r][c] = total
                delta = max(delta, abs(V[r][c] - total))

        V = new_V
        if delta < theta:
            break
    return V

def policy_iteration():
    V = np.zeros((rows, cols))
    policy = [['U' if grid[r][c] is not None and not is_terminal(r, c) else '' for c in range(cols)] for r in range(rows)]

    iteration = 0
    while True:
        print(f"\nPolicy Iteration {iteration}:")
        V = policy_evaluation(policy, V)

        policy_stable = True
        for r in range(rows):
            for c in range(cols):
                if grid[r][c] is None or is_terminal(r, c):
                    continue

                old_action = policy[r][c]
                best_action = old_action
                best_value = float('-inf')

                for a in actions:
                    total = 0
                    for move, prob in transitions[a]:
                        dr, dc = action_delta[move]
                        nr, nc = r + dr, c + dc

                        if not is_valid(nr, nc):
                            nr, nc = r, c

                        reward = grid[nr][nc] if is_terminal(nr, nc) else default_reward
                        total += prob * (reward + gamma * V[nr][nc])

                    if total > best_value:
                        best_value = total
                        best_action = a

                if best_action != old_action:
                    policy_stable = False
                    policy[r][c] = best_action

        print(np.round(V, 2))

        iteration += 1
        if policy_stable:
            break

    return V, policy

# Run policy iteration
V, policy = policy_iteration()

# Print final results
print("\nFinal Value Function:")
print(np.round(V, 2))

print("\nFinal Policy:")
for row in policy:
    print(' '.join([a if a else '.' for a in row]))



Policy Iteration 0:
[[-0.85 -0.69 -0.19  0.  ]
 [-0.87  0.   -0.36  0.  ]
 [-0.88 -0.8  -0.51 -0.95]]

Policy Iteration 1:
[[0.45 0.67 0.91 0.  ]
 [0.27 0.   0.51 0.  ]
 [0.01 0.12 0.28 0.01]]

Policy Iteration 2:
[[0.45 0.67 0.91 0.  ]
 [0.27 0.   0.51 0.  ]
 [0.12 0.12 0.28 0.01]]

Final Value Function:
[[0.45 0.67 0.91 0.  ]
 [0.27 0.   0.51 0.  ]
 [0.12 0.12 0.28 0.01]]

Final Policy:
R R R .
U . U .
U R U L


#10th exp - Use a GitHub library

In [ ]:
!pip install git+https://github.com/Textualize/rich

  Cloning https://github.com/Textualize/rich to /tmp/pip-req-build-7r6s5m0u
  Running command git clone --filter=blob:none --quiet https://github.com/Textualize/rich /tmp/pip-req-build-7r6s5m0u
  Resolved https://github.com/Textualize/rich to commit 8c4d3d1d50047e3aaa4140d0ffc1e0c9f1df5af4
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for rich: filename=rich-14.0.0-py3-none-any.whl size=243266 sha256=680f8935d70de0a4c77c3f2ece957c9a2f46e33ee8242bfa73ca0a80509309b6
  Stored in directory: /tmp/pip-ephem-wheel-cache-u6ucn958/wheels/67/f2/bc/2a74e0230d26bb2dc8bba6c9a74bbaccc5243fc44669902b11
Successfully built rich
  Attempting uninstall: rich
    Found existing installation: rich 13.9.4
    Uninstalling rich-13.9.4:
      Successfully uninstalled rich-13.9.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the 

In [ ]:
from rich.console import Console
from rich.table import Table

console = Console()

table = Table(title="Countries and capitals")

table.add_column("Country", style='cyan')
table.add_column("Capital")

table.add_row("India", "Delhi")
table.add_row("Japan", "Tokyo")

console.print(table)

    Countries and    
      capitals       
┏━━━━━━━━━┳━━━━━━━━━┓
┃ Country ┃ Capital ┃
┡━━━━━━━━━╇━━━━━━━━━┩
│ India   │ Delhi   │
│ Japan   │ Tokyo   │
└─────────┴─────────┘

In [ ]:
!pip install easyAI

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 1.7 MB/s eta 0:00:00


In [ ]:
from easyAI import Game, AI_Player, Human_Player, Negamax

class TicTacToe(TwoPlayersGame):
    def _init_(self, players):
        self.players = players
        self.board = [0] * 9  # 0 = empty, 1 = Player 1, 2 = Player 2
        self.nplayer = 1      # Player 1 starts

    def possible_moves(self):
        return [str(i + 1) for i in range(9) if self.board[i] == 0]

    def make_move(self, move):
        self.board[int(move) - 1] = self.nplayer

    def unmake_move(self, move):  # Required by Negamax
        self.board[int(move) - 1] = 0

    def is_over(self):
        return (self.winner() is not None) or (all(x != 0 for x in self.board))

    def show(self):
        symbols = ['.', 'X', 'O']
        for i in range(3):
            print(" ".join(symbols[self.board[3*i + j]] for j in range(3)))
        print()

    def winner(self):
        wins = [(0,1,2),(3,4,5),(6,7,8), (0,3,6),(1,4,7),(2,5,8), (0,4,8),(2,4,6)]
        for a, b, c in wins:
            if self.board[a] == self.board[b] == self.board[c] != 0:
                return self.board[a]
        return None

    def scoring(self):
        return 100 if self.winner() == self.nplayer else 0

# Depth of 6 is enough for Tic Tac Toe (perfect play)
ai_algo = Negamax(6)

# Play the game (Human vs AI)
game = TicTacToe([Human_Player(), AI_Player(ai_algo)])
game.play()

ImportError: cannot import name 'TwoPlayersGame' from 'easyAI' (/usr/local/lib/python3.11/dist-packages/easyAI/__init__.py)